from django.db import models
from django.utils import timezone

class Supervisor(models.Model):
    #ID should be autogenerated
    #password
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)

# Create your models here.
class Car(models.Model):
    #carNr should be autogenerated
    latitude = models.FloatField()
    longitude = models.FloatField()
    photoOption = models.CharField(max_length=20, default='car-black')

class Employee(models.Model):
    #driverID should be autogenerated
    carID = models.ForeignKey(Car, on_delete=models.DO_NOTHING) #TODO change to something else
    #password
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    #photoOption

class Tour(models.Model):
    #TourID should be autogenerated
    driverID = models.ForeignKey(Employee, on_delete=models.DO_NOTHING)  #TODO change to something else
    carID = models.ForeignKey(Car, on_delete=models.DO_NOTHING) 
    date = models.DateTimeField(default=timezone.now) #TODO change to something else
    start = models.DateTimeField(default=timezone.now) #TODO change to something else
    duration = models.FloatField
    tourType = models.CharField(max_length=20)
    people = models.IntegerField()
    price = models.FloatField()
    envelope = models.FloatField()
    comission = models.FloatField()