# Generated by Django 3.1.4 on 2021-01-13 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.car')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('tourType', models.CharField(max_length=20)),
                ('people', models.IntegerField()),
                ('price', models.FloatField()),
                ('envelope', models.FloatField()),
                ('comission', models.FloatField()),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.car')),
                ('driverID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.employee')),
            ],
        ),
    ]
