# Generated by Django 3.1.4 on 2021-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photoOption',
            field=models.CharField(default='car-black', max_length=20),
        ),
    ]
