# Generated by Django 3.1.4 on 2021-01-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_car_photooption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='car',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
