# Generated by Django 3.1.4 on 2021-01-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_auto_20210114_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='carID',
        ),
    ]
