# Generated by Django 3.1.4 on 2021-01-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_remove_employee_carid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='comission',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='envelope',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start',
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
