# Generated by Django 3.1.4 on 2021-01-14 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervisor', '0006_employeeform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeForm',
        ),
        migrations.AlterField(
            model_name='tour',
            name='driverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
