# Generated by Django 3.1.4 on 2021-01-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0007_auto_20210114_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photoOption',
            field=models.ImageField(default='car-black.png', upload_to='car_pics'),
        ),
    ]
