# Generated by Django 3.1.4 on 2021-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0008_auto_20210117_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photoOption',
            field=models.ImageField(default='default.png', upload_to='car_pics'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tourType',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Silver', max_length=20),
        ),
    ]
