# Generated by Django 3.1.4 on 2021-01-17 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervisor', '0009_auto_20210117_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photoOption',
            field=models.ImageField(default='car-black.jpg', upload_to='cars_pics'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='carID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.car'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='driverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
