# Generated by Django 3.1.4 on 2021-01-17 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervisor', '0010_auto_20210117_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='carID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor.car'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='driverID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
