# Generated by Django 3.1.4 on 2021-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0011_auto_20210117_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='longitude',
        ),
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(default='W01B', max_length=4),
            preserve_default=False,
        ),
    ]
