# Generated by Django 3.1.4 on 2021-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0012_auto_20210117_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
