# Generated by Django 3.1.4 on 2021-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0013_auto_20210117_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photoOption',
            field=models.ImageField(default='car-black.jpg', upload_to='cars_pics/'),
        ),
    ]
